// ============================================================
// slab-scatter.js — Stone Slab Placement
// ============================================================
// Places volcanic stone slab formations (generated by stone-slabs.js)
// across the seabed using a reef mask system and cove detection.
//
// Layout: Main shore-parallel ridge (3-sine meander near X=55)
//         + scattered patch reefs in deeper water
//         + cove clusters in island shoreline indentations
//
// Performance: InstancedMesh, zero per-frame cost — all at init time.
// ============================================================

import * as THREE from 'three';
import { scene, ISLAND_SEED, ISLAND_Z, TILE_SIZE, terrainRefs } from './state.js';
import { sampleSeabedHeight } from './sky-water.js';
import { getTerrainHeight } from './terrain.js';
import {
  generateTieredReefRockVariants,
  LARGE_WORLD_SCALE, MEDIUM_WORLD_SCALE, SMALL_WORLD_SCALE,
  LARGE_HEIGHT_BLOCKS, MEDIUM_HEIGHT_BLOCKS, SMALL_HEIGHT_BLOCKS,
  LARGE_FOOTPRINT, MEDIUM_FOOTPRINT, SMALL_FOOTPRINT,
} from './stone-slabs.js';

// ── Mulberry32 PRNG (identical to rocks.js / sky-water.js) ──
function mulberry32(seed) {
  let s = seed | 0;
  return function () {
    s = (s + 0x6D2B79F5) | 0;
    let t = Math.imul(s ^ (s >>> 15), 1 | s);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

// ── Deterministic position-based hash noise (slab sub-seed) ──
function hashNoise(x, y, z) {
  let n = Math.sin(x * 127.1 + y * 311.7 + z * 74.7 + ISLAND_SEED * 0.3142) * 43758.5453;
  return n - Math.floor(n);
}

// ── Replicated seabed noise table ──────────────────────────────
// Must match sky-water.js exactly so slab placement correlates
// with the raised reef mound patches on the seabed.
const _noiseSize = 4096;
const _noiseTable = new Float32Array(_noiseSize);
{
  const rng = mulberry32(ISLAND_SEED * 2654435761 + 1); // same sub-seed as sky-water.js
  for (let i = 0; i < _noiseSize; i++) _noiseTable[i] = rng();
}

function sbNoise(x, z) {
  return _noiseTable[((Math.floor(x * 7919) + Math.floor(z * 104729)) & 0x7FFFFFFF) % _noiseSize];
}

function sbSmoothNoise(x, z, freq) {
  const fx = x * freq, fz = z * freq;
  const ix = Math.floor(fx), iz = Math.floor(fz);
  const tx = fx - ix, tz = fz - iz;
  const sx = tx * tx * (3 - 2 * tx);
  const sz = tz * tz * (3 - 2 * tz);
  const n00 = sbNoise(ix, iz);
  const n10 = sbNoise(ix + 1, iz);
  const n01 = sbNoise(ix, iz + 1);
  const n11 = sbNoise(ix + 1, iz + 1);
  const a = n00 + (n10 - n00) * sx;
  const b = n01 + (n11 - n01) * sx;
  return a + (b - a) * sz;
}

// ── Smoothstep helper ──
function smoothstep(edge0, edge1, x) {
  const t = Math.max(0, Math.min(1, (x - edge0) / (edge1 - edge0)));
  return t * t * (3 - 2 * t);
}

// ── Scan extents ──
const SCAN_X_MIN = -20, SCAN_X_MAX = 300;
const SCAN_Z_MIN = -300, SCAN_Z_MAX = 250;

// ── Cove edge detection radius (world units) ──
const EDGE_CHECK = 8;

// ── Rock placement caps ──
const MAX_LARGE_ROCKS = 100;
const MAX_MEDIUM_ROCKS = 300;
const MAX_SMALL_ROCKS = 500;

// ── Reef mask thresholds ──
const MASK_DENSE = 0.5;    // large + medium slab
const MASK_MEDIUM = 0.2;   // medium + small slab
const MASK_SPARSE = 0.03;  // small rubble only

// ── Footprint buffer for future coral placement ──
const TRANSITION_BUFFER = 3.0;

// ════════════════════════════════════════════════════════════════
// REEF LAYOUT SYSTEM
// Main shore-parallel ridge + scattered patch reefs
// ════════════════════════════════════════════════════════════════

// Ridge center: 3-sine curve meandering around X=55 (zones B-C)
// Oscillates between ~X=29 and ~X=81
function ridgeCenterX(wz) {
  return 55
    + Math.sin(wz * 0.02) * 18
    + Math.sin(wz * 0.053 + 1.7) * 8
    + Math.sin(wz * 0.011 + 3.1) * 5;
}

// Ridge width: sine-modulated 16-24 world units
function ridgeWidth(wz) {
  return 14 + Math.sin(wz * 0.037 + 0.8) * 2.8;
}

// Combined reef mask at world position (0 = open sand, 1 = dense reef core)
function getReefMask(wx, wz) {
  // ── Main ridge field (quartic falloff from center) ──
  const cx = ridgeCenterX(wz);
  const hw = ridgeWidth(wz) * 0.5;
  const dx = (wx - cx) / hw; // normalized distance from center
  let ridgeField = 0;
  if (Math.abs(dx) < 1) {
    const t = 1 - dx * dx;
    ridgeField = t * t; // quartic: (1 - dx^2)^2
  }
  // Taper to zero at Z endpoints (smooth fadeout, wide reach)
  const zTaper = smoothstep(-295, -260, wz) * smoothstep(245, 210, wz);
  ridgeField *= zTaper;

  // ── Patch reefs (scattered outcrops in deeper water) ──
  // Only activate outside ridge, in zones C-D (X=80-250)
  let patchField = 0;
  if (ridgeField < 0.1 && wx > 60 && wx < 280) {
    const pn = sbSmoothNoise(wx + 2000, -wz + 2000, 0.018);
    if (pn > 0.50) {
      patchField = (pn - 0.50) / (1.0 - 0.50); // normalize to 0-1
      patchField = Math.min(patchField, 0.8);    // cap below 1
    }
  }

  return Math.max(ridgeField, patchField);
}

// ════════════════════════════════════════════════════════════════
// FOOTPRINT MAP
// Tracks which grid cells are ON_ROCK or NEAR_ROCK.
// Kept for future coral placement system.
// ════════════════════════════════════════════════════════════════

const FOOTPRINT_CELL = 2; // world units per cell
const REEF_FOOTPRINT = new Map(); // key: "cellX,cellZ" → { type, topY }

function fpKey(wx, wz) {
  return (Math.floor(wx / FOOTPRINT_CELL)) + ',' + (Math.floor(wz / FOOTPRINT_CELL));
}

// Stamp a slab's footprint into the map
function stampFootprint(wx, wz, radius, topY) {
  const r = radius + TRANSITION_BUFFER;
  const cxMin = Math.floor((wx - r) / FOOTPRINT_CELL);
  const cxMax = Math.ceil((wx + r) / FOOTPRINT_CELL);
  const czMin = Math.floor((wz - r) / FOOTPRINT_CELL);
  const czMax = Math.ceil((wz + r) / FOOTPRINT_CELL);

  for (let cx = cxMin; cx <= cxMax; cx++) {
    for (let cz = czMin; cz <= czMax; cz++) {
      const cellX = cx * FOOTPRINT_CELL + FOOTPRINT_CELL * 0.5;
      const cellZ = cz * FOOTPRINT_CELL + FOOTPRINT_CELL * 0.5;
      const dist = Math.sqrt((cellX - wx) * (cellX - wx) + (cellZ - wz) * (cellZ - wz));

      const key = cx + ',' + cz;
      const existing = REEF_FOOTPRINT.get(key);

      if (dist <= radius) {
        // ON_ROCK — keep highest topY if overlapping
        if (!existing || existing.type !== 'ON_ROCK' || topY > existing.topY) {
          REEF_FOOTPRINT.set(key, { type: 'ON_ROCK', topY });
        }
      } else if (dist <= radius + TRANSITION_BUFFER) {
        // NEAR_ROCK — only set if not already ON_ROCK
        if (!existing) {
          REEF_FOOTPRINT.set(key, { type: 'NEAR_ROCK', topY: null });
        }
      }
    }
  }
}

// ════════════════════════════════════════════════════════════════
// GEOMETRY HELPERS
// ════════════════════════════════════════════════════════════════

function triCount(geo) {
  if (geo.index) return geo.index.count / 3;
  return geo.attributes.position.count / 3;
}

// Depth tinting: simulate underwater light attenuation
function depthTint(seabedY) {
  const depthFrac = Math.max(0, Math.min(1, -seabedY / 40));
  const lightFactor = Math.pow(0.5, depthFrac * 3.5);
  return {
    r: lightFactor,
    g: lightFactor * 0.95 + 0.05,
    b: lightFactor * 0.8 + 0.2,
  };
}

// ── Shared slab material — dark volcanic rock ──
const slabMat = new THREE.MeshStandardMaterial({
  color: new THREE.Color(0.22, 0.21, 0.19),
  roughness: 0.88,
  metalness: 0.04,
  flatShading: true,
});

// ── Paint seabed dark in reef areas ──
// Darkens the seabed's own vertex colors where reef mask is active.
// Zero z-fighting since we modify the existing mesh, not add a new one.
function paintSeabedReefColors() {
  const seabed = terrainRefs.seabedMesh;
  if (!seabed) { console.warn('[slab-scatter] No seabed mesh — skipping reef paint'); return; }

  const geo = seabed.geometry;
  const pos = geo.attributes.position;
  const col = geo.attributes.color;
  if (!col) { console.warn('[slab-scatter] Seabed has no vertex colors'); return; }

  // Target: dark volcanic rock color (matches slabMat)
  const darkR = 0.22, darkG = 0.21, darkB = 0.19;
  let painted = 0;

  for (let i = 0; i < pos.count; i++) {
    // Seabed plane is rotated -pi/2 around X, positioned at Y=-11
    // Local (lx, ly, lz) -> World (lx, lz - 11, -ly)
    const lx = pos.getX(i);
    const ly = pos.getY(i);
    const h = pos.getZ(i); // displacement

    const worldX = lx;
    const worldZ = -ly;

    // Skip shallow water — keep sand color natural (matches slab depth filter)
    if (h > -3) continue;

    const mask = getReefMask(worldX, worldZ);
    if (mask < MASK_SPARSE) continue;

    // Blend strength: smooth ramp from sparse edge to dense core
    const blend = smoothstep(MASK_SPARSE, 0.25, mask) * 0.85;

    const cr = col.getX(i);
    const cg = col.getY(i);
    const cb = col.getZ(i);

    col.setXYZ(i,
      cr * (1 - blend) + darkR * blend,
      cg * (1 - blend) + darkG * blend,
      cb * (1 - blend) + darkB * blend
    );
    painted++;
  }

  col.needsUpdate = true;
  console.log(`[slab-scatter] Painted ${painted} seabed vertices dark in reef areas`);
}

// ════════════════════════════════════════════════════════════════
// COVE DETECTION
// Mirrors tongue warp from terrain.js island shape.
// tongueWarp < 1.0 = concave shoreline indent (cove)
// ════════════════════════════════════════════════════════════════

const PLATEAU_RX = 1;
const PLATEAU_Z_MIN = -54;
const PLATEAU_Z_MAX = 146;

function getTongueWarp(wx, wz) {
  const gx = wx / TILE_SIZE;
  const gz = (wz - ISLAND_Z) / TILE_SIZE;
  const dx = Math.max(0, Math.abs(gx) - PLATEAU_RX);
  const dz = (gz < PLATEAU_Z_MIN) ? (PLATEAU_Z_MIN - gz) : (gz > PLATEAU_Z_MAX) ? (gz - PLATEAU_Z_MAX) : 0;
  const pc = (dx > dz) ? gz : gx;
  return 1.0 + Math.sin(pc * 0.32 + 1.7) * 0.10
             + Math.sin(pc * 0.71 + 4.1) * 0.06
             + Math.sin(pc * 0.13 + 0.5) * 0.08;
}

// ── Reusable objects (zero per-frame allocations) ──
const _dummy = new THREE.Object3D();
const _color = new THREE.Color();
const slabMeshes = [];

// ════════════════════════════════════════════════════════════════
// PUBLIC INIT
// ════════════════════════════════════════════════════════════════

export function initSlabScatter() {
  const t0 = performance.now();

  // ══════════════════════════════════════════════════════════════
  // Stone Slab Placement
  // Generates tiered MC slabs, places via reef mask + cove detection,
  // stamps footprints for future coral system.
  // ══════════════════════════════════════════════════════════════

  console.log('[slab-scatter] Generating tiered MC slab variants...');
  const tiers = generateTieredReefRockVariants(ISLAND_SEED);
  console.log(`[slab-scatter] Slab variants: ${tiers.large.length}L + ${tiers.medium.length}M + ${tiers.small.length}S`);

  // Per-tier placement collectors: variantIndex -> [{px, pz, seabedY, rotY, scaleMul}]
  const largePlacements = tiers.large.map(() => []);
  const mediumPlacements = tiers.medium.map(() => []);
  const smallPlacements = tiers.small.map(() => []);

  let largeCount = 0, mediumCount = 0, smallCount = 0;
  let totalRockTris = 0;

  // ── Darken seabed in reef areas (zero z-fighting) ──
  console.log('[slab-scatter] Painting seabed dark in reef areas...');
  paintSeabedReefColors();

  // ── Base layer: composite clusters of existing large/medium slabs ──
  // Each cluster spot places 3-5 overlapping slabs with varied height to
  // form an irregular rocky bed. Some members are taller (ridges/extrusions),
  // others are flat bases. Uses the same proven MC geometries.
  const BASE_STEP = 10;
  const baseCenters = []; // overlap prevention + lift detection
  const BASE_MIN_DIST = 22;
  let baseSpots = 0;
  const MAX_BASE_SPOTS = 250;

  const baseLargePlacements = tiers.large.map(() => []);
  const baseMediumPlacements = tiers.medium.map(() => []);

  for (let wx = SCAN_X_MIN; wx <= SCAN_X_MAX; wx += BASE_STEP) {
    for (let wz = SCAN_Z_MIN; wz <= SCAN_Z_MAX; wz += BASE_STEP) {
      if (baseSpots >= MAX_BASE_SPOTS) break;

      const jx = (hashNoise(wx * 5.3, wz * 7.1, 300) - 0.5) * BASE_STEP * 0.7;
      const jz = (hashNoise(wx * 8.7, wz * 4.3, 301) - 0.5) * BASE_STEP * 0.7;
      const px = wx + jx;
      const pz = wz + jz;

      const h = sampleSeabedHeight(px, pz);
      if (h > -3) continue;

      const mask = getReefMask(px, pz);
      if (mask < MASK_MEDIUM) continue;

      // Overlap prevention — clusters don't stack
      let tooClose = false;
      for (let c = 0; c < baseCenters.length; c++) {
        const dx = px - baseCenters[c][0], dz = pz - baseCenters[c][1];
        if (dx * dx + dz * dz < BASE_MIN_DIST * BASE_MIN_DIST) {
          tooClose = true;
          break;
        }
      }
      if (tooClose) continue;

      baseCenters.push([px, pz]);
      baseSpots++;

      // Generate cluster of 3-5 overlapping slabs around this center
      const clusterSize = 3 + Math.floor(hashNoise(wx * 91.3, wz * 87.1, 310) * 3);
      for (let ci = 0; ci < clusterSize; ci++) {
        const offX = (hashNoise(wx * 51.3 + ci * 7.1, wz * 43.7, 311) - 0.5) * 14;
        const offZ = (hashNoise(wx * 37.1 + ci * 11.3, wz * 53.3, 312) - 0.5) * 14;
        const subPx = px + offX;
        const subPz = pz + offZ;

        const subH = sampleSeabedHeight(subPx, subPz);
        if (subH > -3) continue; // don't place cluster members on slopes

        const subSeabedY = -11 + subH;
        const subRotY = hashNoise(wx * 67.3 + ci * 13.7, wz * 71.1, 313) * Math.PI * 2;
        const subScaleMul = 0.80 + hashNoise(wx * 73.1 + ci * 17.3, wz * 61.7, 314) * 0.40;

        // Height variation: ~40% are taller ridges, rest are flat base
        const ridgeRoll = hashNoise(wx * 83.1 + ci * 19.7, wz * 79.3, 315);
        const hsNoise = hashNoise(wx * 89.3 + ci * 23.1, wz * 83.7, 316);
        const subHeightScale = ridgeRoll > 0.6
          ? 0.38 + hsNoise * 0.12   // ridge: 0.38-0.50
          : 0.22 + hsNoise * 0.10;  // flat:  0.22-0.32

        const subSinkDepth = 0.9 + hashNoise(wx * 97.1 + ci * 29.3, wz * 91.7, 317) * 0.4;

        // First 2 always large for coverage, rest mix large/medium
        const useLarge = ci < 2 || hashNoise(wx * 101.3 + ci * 31.7, wz * 97.3, 318) > 0.4;
        if (useLarge) {
          const vi = Math.floor(hashNoise(wx * 107.1 + ci * 37.3, wz * 103.7, 319) * tiers.large.length) % tiers.large.length;
          baseLargePlacements[vi].push({ px: subPx, pz: subPz, seabedY: subSeabedY, rotY: subRotY, scaleMul: subScaleMul, heightScale: subHeightScale, sinkDepth: subSinkDepth });
          totalRockTris += triCount(tiers.large[vi]);
        } else {
          const vi = Math.floor(hashNoise(wx * 107.1 + ci * 37.3, wz * 103.7, 319) * tiers.medium.length) % tiers.medium.length;
          baseMediumPlacements[vi].push({ px: subPx, pz: subPz, seabedY: subSeabedY, rotY: subRotY, scaleMul: subScaleMul, heightScale: subHeightScale, sinkDepth: subSinkDepth });
          totalRockTris += triCount(tiers.medium[vi]);
        }
      }
    }
    if (baseSpots >= MAX_BASE_SPOTS) break;
  }

  console.log(`[slab-scatter] Base layer: ${baseSpots} cluster spots`);

  // ── Grid scan: place slabs based on reef mask + cove detection ──
  const ROCK_STEP = 6; // tighter than coral grid for dense, interconnected coverage
  for (let wx = SCAN_X_MIN; wx <= SCAN_X_MAX; wx += ROCK_STEP) {
    for (let wz = SCAN_Z_MIN; wz <= SCAN_Z_MAX; wz += ROCK_STEP) {
      // Base jitter for reef-zone slabs
      let jitterX = (hashNoise(wx * 7.1, wz * 11.3, 200) - 0.5) * ROCK_STEP * 0.8;
      let jitterZ = (hashNoise(wx * 9.7, wz * 5.3, 201) - 0.5) * ROCK_STEP * 0.8;

      // Pre-sample height at grid center to detect deep zones early
      const hCenter = sampleSeabedHeight(wx, wz);

      // Deep water: massive jitter to break grid patterns completely
      if (hCenter < -12) {
        jitterX = (hashNoise(wx * 23.1, wz * 19.7, 207) - 0.5) * ROCK_STEP * 2.5;
        jitterZ = (hashNoise(wx * 17.3, wz * 29.1, 208) - 0.5) * ROCK_STEP * 2.5;
      }

      const px = wx + jitterX;
      const pz = wz + jitterZ;

      const h = sampleSeabedHeight(px, pz);
      const seabedY = -11 + h;

      // ── Depth-based slope exclusion ──
      // The slope/shelf between island and reef is shallow water (h > -3 = depth < 14m).
      // The reef floor sits at Zone C (h ≈ -8, depth ~19m) and deeper.
      // Skipping h > -3 clears the entire visible slope regardless of reef mask overlap.
      //
      // ── Cove exception ──
      // Coves are concave shoreline pockets where the shelf drops off faster.
      // Near the terrain edge with tongueWarp < 0.95, moderate depth (h -6 to 0).
      const atTerrainEdge =
        getTerrainHeight(px - EDGE_CHECK, pz) > 0.1 ||
        getTerrainHeight(px + EDGE_CHECK, pz) > 0.1 ||
        getTerrainHeight(px, pz - EDGE_CHECK) > 0.1 ||
        getTerrainHeight(px, pz + EDGE_CHECK) > 0.1;
      const inCove = atTerrainEdge && getTongueWarp(px, pz) < 0.95 && h > -6 && h <= 0;

      // Hard depth filter — clears ALL shallow positions unless in a cove
      if (h > -3 && !inCove) continue;

      const mask = getReefMask(px, pz);

      // Deep water (h < -12): sparse slabs trailing into the abyss
      const onDeepFloor = h < -12;

      if (inCove) {
        // Cove placement: ~20% density for small/medium slabs
        const coveRoll = hashNoise(wx * 23.1, wz * 19.7, 206);
        if (coveRoll > 0.20) continue;
      } else if (onDeepFloor) {
        if (mask >= MASK_SPARSE) { /* in a patch reef — normal placement */ }
        else {
          const deepRoll = hashNoise(wx * 31.3, wz * 27.1, 209);
          if (deepRoll > 0.04) continue; // ~4% chance — very sparse deep rubble
        }
      } else {
        if (mask < MASK_SPARSE) continue; // reef zone open sand — skip
      }

      const rotY = hashNoise(wx * 41.3, wz * 29.7, 205) * Math.PI * 2;
      const densityRoll = hashNoise(wx * 3.1, wz * 5.7, 202);
      const varRoll = hashNoise(wx * 61.7, wz * 43.1, 203);
      // Cove/deep slabs are smaller (0.6-0.8), reef slabs normal (0.85-1.15)
      const offReef = inCove || (onDeepFloor && mask < MASK_SPARSE);
      const scaleMul = offReef
        ? 0.6 + hashNoise(wx * 81.1, wz * 63.3, 204) * 0.2
        : 0.85 + hashNoise(wx * 81.1, wz * 63.3, 204) * 0.3;

      let placed = false;

      // Cove / deep floor scatter: small + medium slabs
      if (inCove) {
        // Coves get small and medium slabs for visual interest
        if (!placed && mediumCount < MAX_MEDIUM_ROCKS && densityRoll < 0.35) {
          const vi = Math.floor(varRoll * tiers.medium.length) % tiers.medium.length;
          mediumPlacements[vi].push({ px, pz, seabedY, rotY, scaleMul });
          mediumCount++;
          totalRockTris += triCount(tiers.medium[vi]);
          const topY = seabedY + MEDIUM_HEIGHT_BLOCKS * MEDIUM_WORLD_SCALE * scaleMul * 0.20;
          stampFootprint(px, pz, MEDIUM_FOOTPRINT * scaleMul, topY);
          placed = true;
        }
        if (!placed && smallCount < MAX_SMALL_ROCKS) {
          const vi = Math.floor(varRoll * tiers.small.length) % tiers.small.length;
          smallPlacements[vi].push({ px, pz, seabedY, rotY, scaleMul });
          smallCount++;
          totalRockTris += triCount(tiers.small[vi]);
          const topY = seabedY + SMALL_HEIGHT_BLOCKS * SMALL_WORLD_SCALE * scaleMul * 0.22;
          stampFootprint(px, pz, SMALL_FOOTPRINT * scaleMul, topY);
          placed = true;
        }
      } else if (offReef) {
        // Deep floor scatter: only small rubble
        if (smallCount < MAX_SMALL_ROCKS) {
          const vi = Math.floor(varRoll * tiers.small.length) % tiers.small.length;
          smallPlacements[vi].push({ px, pz, seabedY, rotY, scaleMul });
          smallCount++;
          totalRockTris += triCount(tiers.small[vi]);
          const topY = seabedY + SMALL_HEIGHT_BLOCKS * SMALL_WORLD_SCALE * scaleMul * 0.22;
          stampFootprint(px, pz, SMALL_FOOTPRINT * scaleMul, topY);
          placed = true;
        }
      } else if (mask > MASK_DENSE) {
        // Dense core: try large slab first, then medium fill
        if (!placed && largeCount < MAX_LARGE_ROCKS && densityRoll < 0.40) {
          const vi = Math.floor(varRoll * tiers.large.length) % tiers.large.length;
          largePlacements[vi].push({ px, pz, seabedY, rotY, scaleMul });
          largeCount++;
          totalRockTris += triCount(tiers.large[vi]);
          const topY = seabedY + LARGE_HEIGHT_BLOCKS * LARGE_WORLD_SCALE * scaleMul * 0.18;
          stampFootprint(px, pz, LARGE_FOOTPRINT * scaleMul, topY);
          placed = true;
        }
        if (!placed && mediumCount < MAX_MEDIUM_ROCKS && densityRoll < 0.65) {
          const vi = Math.floor(varRoll * tiers.medium.length) % tiers.medium.length;
          mediumPlacements[vi].push({ px, pz, seabedY, rotY, scaleMul });
          mediumCount++;
          totalRockTris += triCount(tiers.medium[vi]);
          const topY = seabedY + MEDIUM_HEIGHT_BLOCKS * MEDIUM_WORLD_SCALE * scaleMul * 0.20;
          stampFootprint(px, pz, MEDIUM_FOOTPRINT * scaleMul, topY);
          placed = true;
        }
      } else if (mask > MASK_MEDIUM) {
        // Medium zone: medium slab or small fill
        if (!placed && mediumCount < MAX_MEDIUM_ROCKS && densityRoll < 0.55) {
          const vi = Math.floor(varRoll * tiers.medium.length) % tiers.medium.length;
          mediumPlacements[vi].push({ px, pz, seabedY, rotY, scaleMul });
          mediumCount++;
          totalRockTris += triCount(tiers.medium[vi]);
          const topY = seabedY + MEDIUM_HEIGHT_BLOCKS * MEDIUM_WORLD_SCALE * scaleMul * 0.20;
          stampFootprint(px, pz, MEDIUM_FOOTPRINT * scaleMul, topY);
          placed = true;
        }
        if (!placed && smallCount < MAX_SMALL_ROCKS && densityRoll < 0.70) {
          const vi = Math.floor(varRoll * tiers.small.length) % tiers.small.length;
          smallPlacements[vi].push({ px, pz, seabedY, rotY, scaleMul });
          smallCount++;
          totalRockTris += triCount(tiers.small[vi]);
          const topY = seabedY + SMALL_HEIGHT_BLOCKS * SMALL_WORLD_SCALE * scaleMul * 0.22;
          stampFootprint(px, pz, SMALL_FOOTPRINT * scaleMul, topY);
          placed = true;
        }
      } else if (mask > MASK_SPARSE) {
        // Sparse transition: small rubble only
        if (!placed && smallCount < MAX_SMALL_ROCKS && densityRoll < 0.55) {
          const vi = Math.floor(varRoll * tiers.small.length) % tiers.small.length;
          smallPlacements[vi].push({ px, pz, seabedY, rotY, scaleMul });
          smallCount++;
          totalRockTris += triCount(tiers.small[vi]);
          const topY = seabedY + SMALL_HEIGHT_BLOCKS * SMALL_WORLD_SCALE * scaleMul * 0.22;
          stampFootprint(px, pz, SMALL_FOOTPRINT * scaleMul, topY);
          placed = true;
        }
      }

    }
  }

  console.log(`[slab-scatter] Slabs placed: ${baseSpots} base clusters + ${largeCount}L + ${mediumCount}M + ${smallCount}S`);
  console.log(`[slab-scatter] Slab tris: ~${(totalRockTris / 1000).toFixed(0)}K | Footprint cells: ${REEF_FOOTPRINT.size}`);

  // ── Build slab InstancedMeshes ──
  let slabDrawCalls = 0;

  function buildSlabInstances(geos, placements, worldScale, heightScale, sinkDepth) {
    for (let v = 0; v < geos.length; v++) {
      const group = placements[v];
      if (group.length === 0) continue;

      const im = new THREE.InstancedMesh(geos[v], slabMat, group.length);
      im.castShadow = false;
      im.receiveShadow = false;

      for (let i = 0; i < group.length; i++) {
        const p = group[i];
        const s = worldScale * p.scaleMul;
        const hs = p.heightScale !== undefined ? p.heightScale : heightScale;
        const sd = p.sinkDepth !== undefined ? p.sinkDepth : sinkDepth;
        _dummy.position.set(p.px, p.seabedY - sd, p.pz);
        _dummy.rotation.set(0, p.rotY, 0);
        _dummy.scale.set(s, s * hs, s);
        _dummy.updateMatrix();
        im.setMatrixAt(i, _dummy.matrix);

        // Slab tinting — depth-based attenuation
        const tint = depthTint(p.seabedY);
        _color.setRGB(tint.r * 0.75, tint.g * 0.75, tint.b * 0.75);
        im.setColorAt(i, _color);
      }

      im.instanceMatrix.needsUpdate = true;
      if (im.instanceColor) im.instanceColor.needsUpdate = true;
      scene.add(im);
      slabMeshes.push(im);
      slabDrawCalls++;
    }
  }

  // ── Lift scattered slabs near base clusters so they sit on top ──
  const BASE_LIFT = 0.5;
  const BASE_RADIUS_SQ = 12 * 12;

  function liftOverBase(placements) {
    for (const group of placements) {
      for (const p of group) {
        for (let c = 0; c < baseCenters.length; c++) {
          const dx = p.px - baseCenters[c][0], dz = p.pz - baseCenters[c][1];
          if (dx * dx + dz * dz < BASE_RADIUS_SQ) {
            p.seabedY += BASE_LIFT;
            break;
          }
        }
      }
    }
  }

  liftOverBase(largePlacements);
  liftOverBase(mediumPlacements);
  liftOverBase(smallPlacements);

  // Base cluster layer (reuses large/medium geos as flat overlapping slabs)
  buildSlabInstances(tiers.large, baseLargePlacements, LARGE_WORLD_SCALE, 0.35, 1.0);
  buildSlabInstances(tiers.medium, baseMediumPlacements, MEDIUM_WORLD_SCALE, 0.35, 0.8);
  // Scattered slabs on top
  buildSlabInstances(tiers.large, largePlacements, LARGE_WORLD_SCALE, 0.45, 0.3);
  buildSlabInstances(tiers.medium, mediumPlacements, MEDIUM_WORLD_SCALE, 0.50, 0.1);
  buildSlabInstances(tiers.small, smallPlacements, SMALL_WORLD_SCALE, 0.55, 0.0);

  const totalTime = performance.now() - t0;
  console.log(`[slab-scatter] Complete: ${slabDrawCalls} draw calls, ~${(totalRockTris / 1_000_000).toFixed(2)}M tris (${totalTime.toFixed(0)}ms)`);
}
